import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Photoshop UXP adapter parses and requests autonomous local path access", async () => {
  const source = await readFile("adapters/photoshop-uxp/main.js", "utf8");
  assert.doesNotThrow(() => new Function(source));
  assert.match(source, /createDocument/);
  assert.match(source, /createTextLayer/);
  assert.match(source, /resizeImage/);
  assert.match(source, /placedLayerReplaceContents/);
  assert.match(source, /placedLayerRelinkToFile/);
  assert.match(source, /placedLayerEditContents/);
  assert.match(source, /newPlacedLayer/);
  assert.match(source, /layer\.translate/);
  assert.match(source, /bringToFront/);
  assert.match(source, /sendToBack/);
  assert.match(source, /createLayer\(kind/);
  assert.match(source, /characterStyle/);
  assert.match(source, /paragraphStyle/);
  assert.match(source, /applyTextStyleRanges/);
  assert.match(source, /textStyleRange/);
  assert.match(source, /fontPostScriptName/);
  assert.match(source, /adjustmentLayerDescriptor/);
  assert.match(source, /hueSatAdjustmentV2/);
  assert.match(source, /levelsAdjustment/);
  assert.match(source, /applyAddNoise/);
  assert.match(source, /async function paintRetouch/);
  assert.match(source, /contentAware/);
  assert.match(source, /strokePath/);
  assert.match(source, /manageVectorPath/);
  assert.match(source, /doc\.pathItems\.add/);
  assert.match(source, /makeSelection/);
  assert.match(source, /fillPath/);
  assert.match(source, /makeClippingPath/);
  assert.match(source, /ToolType\.CLONESTAMP/);
  assert.match(source, /ToolType\.HEALINGBRUSH/);
  assert.match(source, /selection\.contract/);
  assert.match(source, /selection\.expand/);
  assert.match(source, /selection\.feather/);
  assert.match(source, /selection\.grow/);
  assert.match(source, /selection\.smooth/);
  assert.match(source, /selection\.makeWorkPath/);
  assert.match(source, /selection\.resizeBoundary/);
  assert.match(source, /selection\.rotateBoundary/);
  assert.match(source, /saveAs\.png/);
  assert.match(source, /executeAsModal/);

  const manifest = JSON.parse(await readFile("adapters/photoshop-uxp/manifest.json", "utf8"));
  assert.equal(manifest.manifestVersion, 5);
  assert.equal(manifest.requiredPermissions.localFileSystem, "fullAccess");
  assert.equal(manifest.host.minVersion, "24.2.0");
});

test("Photoshop adapter retains descriptor escape hatch", async () => {
  const source = await readFile("adapters/photoshop-uxp/main.js", "utf8");
  assert.match(source, /runBatchPlay/);
  assert.match(source, /params\.descriptors/);
  assert.match(source, /action\.batchPlay/);
});
